---
toggle_key_combination: '<ctrl>+q'  # Hotkey for toggling the bot on and off.

input_key_left: 'a'                 # Key for "move left" in Brawlhalla.
input_key_right: 'd'                # Key for "move right" in Brawlhalla.
input_key_aim_up: 'w'               # Key for "aim up" in Brawlhalla.
input_key_down: 's'                 # Key for "down" in Brawlhalla.
input_key_jump: 'j'                 # Key for "jump" in Brawlhalla.

input_key_light_attack: 'h'         # Key for "light attack" in Brawlhalla.
input_key_heavy_attack: 'j'         # Key for "heavy attack" in Brawlhalla.
input_key_throw: 'k'                # Key for "throw/pickup" in Brawlhalla.
input_key_dodge: 'l'                # Key for "dodge" in Brawlhalla.

input_keys: [input_key_left, input_key_right, input_key_aim_up, input_key_down, input_key_jump, input_key_light_attack, input_key_heavy_attack, input_key_throw, input_key_dodge]
