---
ffa: "False"                        # Set to "False" for custom-game bot, set to "True" for FFA bot.
toggle_key_combination: '<ctrl>+q'  # Hotkey for toggling the bot on and off.

input_key_left: 'o'                 # Key for "Move left" in Brawlhalla.
input_key_right: 'e'                # Key for "Move right" in Brawlhalla.
input_key_up: 'u'                   # Key for "Aim up" in Brawlhalla.
input_key_down: 'a'                 # Key for "Down" in Brawlhalla.
input_key_jump: 'space'             # Key for "Jump" in Brawlhalla.

input_key_light_attack: 'h'         # Key for "Light attack" in Brawlhalla.
input_key_heavy_attack: 't'         # Key for "Heavy attack" in Brawlhalla.
input_key_throw: 's'                # Key for "Throw/pickup" in Brawlhalla.
input_key_dodge: 'n'                # Key for "Dodge" in Brawlhalla.

input_keys: [input_key_left, input_key_right, input_key_up, input_key_down, input_key_jump, input_key_light_attack, input_key_heavy_attack, input_key_throw, input_key_dodge]  # List of the input keys to use in the bot.
